#---------------------------
# Material-T
# 一个基于Material Design风格的主题
# Author: invom
# Github: https://github.com/invom/Material-T
#---------------------------

#---------------------------
# 全局
# Site
#---------------------------
favicon: ../img/favicon.png
apple_touch_icon: ../img/apple-icon.png


#---------------------------
# 首页
# Index Page
#---------------------------
subtitle:
  enable: true

index_head_img: https://i.loli.net/2018/10/13/5bc1af44bb064.jpg 

#---------------------------
# 导航栏
# Head Navbar
#---------------------------
menu:
  enable: true
  list:
    archives: /archives/
    #Projects: /projects/
    about: /about/
  

social_icons:
  enable: true
  tips: 'See me here'
  list: 
    github: 
    twitter: 
  

#---------------------------
# 文章页
# Post Page
#---------------------------
comments_type: 'disqus'
disqus: 
  shortname:

#---------------------------
# 归档页
# Archive Page
#---------------------------
archive_head_img: https://i.loli.net/2018/10/18/5bc8833e92370.jpg


#---------------------------
# 关于页
# About Page
#---------------------------
about:
  head_img: https://i.loli.net/2018/10/18/5bc8833e75953.jpg
  avatar: https://i.loli.net/2018/10/12/5bc074d44218b.jpg 
  name: 
  job:  
  introduce: 
  extension: 

about_icons: 
  github: 
  twitter: 


#---------------------------
# 底部信息
# Footer
#---------------------------
footer: <b>多喝热水</b>