#---------------------------
# Material-T
# 一个基于Material Design风格的主题
# Author: invom
# Github: https://github.com/invom/Material-T
#---------------------------


#---------------------------
# 首页
# Index Page
#---------------------------
subtitle:
  enable: true

index_head_img: https://i.loli.net/2018/10/13/5bc1af44bb064.jpg 

#---------------------------
# 导航栏
# Head Navbar
#---------------------------
menu:
  enable: true
  list:
    archives: /archives/
    #Projects: /projects/
    about: /about/
  

social_icons:
  enable: true
  list: 
    github: https://github.com/invom
    twitter:
    telegram: 
  

#---------------------------
#文章页
#Post Page
#---------------------------
comments_type: 'disqus'
disqus: 
  shortname:



#---------------------------
#关于页
#About Page
#---------------------------
about:
  avatar: https://i.loli.net/2018/10/12/5bc074d44218b.jpg 
  name: MyName
  job:  MyJob
  introduce: '我还是个孩子啊。'
  extension:

about_icons: 
  facebook: https://facebook.com
  weibo: https://weibo.com
  weixin: aaaa


#---------------------------
#底部信息
#footer
#---------------------------
footer: <a href="https://hexo.io/zh-cn/">HEXO</a>